config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  post 'sign_up', to: 'users#create'
  get 'sign_up', to: 'users#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new'
  get 'user/change_password', to: 'users#edit_password'
  post 'user/change_password', to: 'users#change_password'
  get 'user/update', to: 'users#edit'
  post 'user/update', to: 'users#update'
  delete 'user/delete', to: 'users#destroy'
  #all of dashboard routes
  get 'dashboard', to: 'dashboards#index'
  get 'dashboard/add_user', to: 'dashboards#new_user'
  post 'dashboard/add_user', to: 'dashboards#create_user'
  get 'dashboard/show_user', to: 'dashboards#show_user'
  get 'dashboard/change_status/:id', to: 'dashboards#change_status'
  delete 'dashboard/delete_user/:id', to: 'dashboards#delete_user'
  #all of course related routes
  get 'dashboard/add_course', to: 'courses#new_course'
  post 'dashboard/add_course', to: 'courses#create_course'
  get 'dashboard/show_course', to: 'courses#show_course'
  get 'dashboard/edit_course/:id', to: 'courses#edit_course'
  patch 'dashboard/edit_course/:id', to: 'courses#save_course'
  delete 'dashboard/delete_course/:id', to: 'courses#destroy_course'
  get 'dashboard/show_a_course/:id', to: 'courses#show_single_course'
  #all of lesson related routes
  post 'dashboard/add_lesson/:course_id', to: 'lessons#create_lesson'
  delete 'dashboard/delete_lesson/:lesson_id', to: 'lessons#destroy_lesson'
  get 'dashboard/edit_lesson/:lesson_id', to: 'lessons#edit_lesson'
  patch 'dashboard/edit_lesson/:lesson_id', to: 'lessons#save_lesson'
  #all of content related routes
  post 'dashboard/save_content/:lesson_id', to: 'contents#create_content'
  delete 'dashboard/delete_content/:content_id', to: 'contents#destroy_content'
  #all of enrollment related routes
  get 'dashboard/enroll_course/:course_id', to: 'enrollments#index'
  post 'dashboard/enroll_course/:course_id', to: 'enrollments#enroll'
  post 'dashboard/assign_to_all/:course_id', to: 'enrollments#assign_all_user'
  delete 'dashboard/unassign_to_all/:course_id', to: 'enrollments#unassign_all_user'
  delete 'dashboard/dis_enroll_course/:course_id', to: 'enrollments#dis_enroll'
  post 'dashboard/complete_lesson/:lesson_id', to: 'enrollments#complete_lesson'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'up' => 'rails/health#show', as: :rails_health_check
  resources :confirmations, only: %i[create edit new], param: :confirmation_token
  resources :passwords, only: %i[create edit new update], param: :password_reset_token
  match "*path", to: "application#not_found", via: :all, constraints: ->(req) { !req.path.start_with?('/rails/active_storage') }
end

app/views/shared/_form_errors.html.erb
<!-- app/views/shared/_form_errors.html.erb -->
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li class="text-danger"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">LMS</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mynavbar">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-link">
            <%= link_to I18n.t('views.button.dashboard'), dashboard_show_user_path, class: 'btn btn-light' %>
          </li>
          <li class="nav-link">
            <%= link_to I18n.t('views.button.update_profile'), user_update_path, class: 'btn btn-light' %>
          </li>
          <li class="nav-link">
            <%= link_to I18n.t('views.button.change_password'), user_change_password_path, class: 'btn btn-light' %>
          </li>
          <li class="nav-link">
            <%= form_with url: logout_path, method: :delete do |form| %>
              <%= form.button I18n.t('views.button.logout'), class: 'btn btn-light' %>
            <% end %>
          </li>
        <% else %>
          <li class="nav-link">
            <%= link_to I18n.t('views.button.login'), login_path %>
          </li>
          <li class="nav-link">
            <%= link_to I18n.t('views.button.sign_up'), sign_up_path %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="text" placeholder= <%= I18n.t('views.placeholder.search') %>>
        <button class="btn btn-primary" type="button"><%= I18n.t('views.placeholder.search') %></button>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_navbar_right.html.erb
<div class="row" style="border-left: 2px solid gray">
  <div class="col-12 m-2 bg-light p-1 rounded">
    <%= link_to I18n.t('views.button.users'), dashboard_show_user_path %>
  </div>
  <% if policy(:dashboard).new_user? %>
    <div class="col-12 m-2 bg-light p-1 rounded">
      <%= link_to I18n.t('views.button.add_user'), dashboard_add_user_path %>
    </div>
  <% end %>
  <div class="col-12 m-2 bg-light p-1 rounded">
    <%= link_to I18n.t('views.button.courses'), "/dashboard/show_course" %>
  </div>
  <% if policy(Course).new_course? %>
    <div class="col-12 m-2 bg-light p-1 rounded">
      <%= link_to I18n.t('views.button.add_course'), "/dashboard/add_course" %>
    </div>
  <% end %>
</div>

app/views/shared/_show_flash_message.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-warning">
    <%= flash[:error] %>
  </div>
<% elsif flash[:message] %>
  <div class="alert alert-info">
    <%= flash[:message] %>
  </div>
<% end %>