config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  post 'sign_up', to: 'users#create'
  get 'sign_up', to: 'users#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new'
  get 'user/change_password', to: 'users#edit_password'
  post 'user/change_password', to: 'users#change_password'
  get 'user/update', to: 'users#edit'
  post 'user/update', to: 'users#update'
  delete 'user/delete', to: 'users#destroy'
  #all of dashboard routes
  get 'dashboard', to: 'dashboards#index'
  get 'dashboard/add_user', to: 'dashboards#new_user'
  post 'dashboard/add_user', to: 'dashboards#create_user'
  get 'dashboard/show_user', to: 'dashboards#show_user'
  get 'dashboard/change_status/:id', to: 'dashboards#change_status'
  delete 'dashboard/delete_user/:id', to: 'dashboards#delete_user'
  #all of course related routes
  get 'dashboard/add_course', to: 'courses#new_course'
  post 'dashboard/add_course', to: 'courses#create_course'
  get 'dashboard/show_course', to: 'courses#show_course'
  get 'dashboard/edit_course/:id', to: 'courses#edit_course'
  patch 'dashboard/edit_course/:id', to: 'courses#save_course'
  delete 'dashboard/delete_course/:id', to: 'courses#destroy_course'
  get 'dashboard/show_a_course/:id', to: 'courses#show_single_course'
  #all of lesson related routes
  post 'dashboard/add_lesson/:course_id', to: 'lessons#create_lesson'
  delete 'dashboard/delete_lesson/:lesson_id', to: 'lessons#destroy_lesson'
  get 'dashboard/edit_lesson/:lesson_id', to: 'lessons#edit_lesson'
  patch 'dashboard/edit_lesson/:lesson_id', to: 'lessons#save_lesson'
  #all of content related routes
  post 'dashboard/save_content/:lesson_id', to: 'contents#create_content'
  delete 'dashboard/delete_content/:content_id', to: 'contents#destroy_content'
  #all of enrollment related routes
  get 'dashboard/enroll_course/:course_id', to: 'enrollments#index'
  post 'dashboard/enroll_course/:course_id', to: 'enrollments#enroll'
  post 'dashboard/assign_to_all/:course_id', to: 'enrollments#assign_all_user'
  delete 'dashboard/unassign_to_all/:course_id', to: 'enrollments#unassign_all_user'
  delete 'dashboard/dis_enroll_course/:course_id', to: 'enrollments#dis_enroll'
  post 'dashboard/complete_lesson/:lesson_id', to: 'enrollments#complete_lesson'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'up' => 'rails/health#show', as: :rails_health_check
  resources :confirmations, only: %i[create edit new], param: :confirmation_token
  resources :passwords, only: %i[create edit new update], param: :password_reset_token
  match "*path", to: "application#not_found", via: :all, constraints: ->(req) { !req.path.start_with?('/rails/active_storage') }
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  layout 'dashboard'
  before_action :authenticate_user!

  def new_course
    @page_title = I18n.t('controller.courses.new_course.add_new_course')
    @course = Course.new
    authorize @course
  end

  def create_course
    @user = current_user
    @course = @user.courses.new(course_params)
    authorize @course if @course.present?
    @enrollment = @course.enrollments.build(user: @user, enrollment_type: USER_TYPE_INSTRUCTOR)
    if @course.save && @enrollment.save
      flash[:notice] = I18n.t('controller.courses.create_course.course_added')
      redirect_to dashboard_show_course_path
    else
      render :new_course, status: :unprocessable_entity
    end
  end

  def show_course
    @page_title = I18n.t('controller.courses.show_course.show_courses')
    @courses = policy_scope(Course)
    authorize @courses
  end

  def show_single_course
    @page_title = I18n.t('controller.courses.show_single_course.show_course')
    @course = Course.includes(:lessons).find_by(id: params[:id])
    return invalid_params unless @course.present?

    authorize @course if @course.present?
    @lesson = Lesson.new
    @content = Content.new
  end

  def edit_course
    @page_title = I18n.t('controller.courses.edit_course.edit_a_course')
    @course = Course.find_by(id: params[:id])
    return invalid_params unless @course.present?

    authorize @course
  end

  def save_course
    @course = Course.find_by(id: params[:id])
    return invalid_params unless @course.present?

    authorize @course if @course.present?
    if @course.update(course_params)
      flash[:notice] = I18n.t('controller.courses.save_course.success_notice')
      redirect_to dashboard_show_course_path
    else
      render :new_course, status: :unprocessable_entity
    end
  end

  def destroy_course
    @course = Course.find_by(id: params[:id])
    return invalid_params unless @course.present?

    authorize @course if @course.present?
    instructor = Enrollment.find_by(course_id: @course.id, enrollment_type: USER_TYPE_INSTRUCTOR)
    if @course.destroy
      UserMailer.send_mail_for_delete_course(instructor.user, @course).deliver_now
      flash[:notice] = I18n.t('controller.courses.delete_course.success_notice')
      redirect_to dashboard_show_course_path
    else
      flash[:notice] = I18n.t('errors.messages.try_again')
      redirect_to dashboard_show_course_path
    end
  end

  private

  def course_params
    params.require(:course).permit(:title, :description)
  end
end

app/views/courses/_delete_content_button.html.erb
<%= form_with url: "/dashboard/delete_content/#{content.id}", method: :delete do |form| %>
  <%= form.button I18n.t('views.button.delete'), class: 'nav-link text-danger text-decoration-underline', data: { content_id: content.id } %>
<% end %>

app/views/courses/_delete_modal.html.erb
<div class="modal" id="myModal<%= lesson.id %>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= I18n.t('views.inner_text.courses.delete_course') %></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body" style="font-size: small;">
        <%= I18n.t('views.inner_text.courses.delete_confirmation_message') %>
      </div>
      <div class="modal-footer" style="font-size: medium;">
        <%= form_with url: "/dashboard/delete_lesson/#{lesson.id}", method: :delete do |form| %>
          <%= form.button "Delete", class: 'btn btn-danger' %>
        <% end %>
        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/courses/_new_content_collapse.html.erb
<div id="demo<%=lesson.id %>" class="collapse">
  <div style="width: 600px;">
    <div class="card m-3" style="font-size: medium;">
      <div class="card-body">
        <%= form_with(model: @content, url: "/dashboard/save_content/#{lesson.id}", multipart: true) do |form| %>
          <div class="mt-4">
            <%= form.label I18n.t('activerecord.attributes.title') %> </br>
            <%= form.text_field :title, style: 'width:100%', placeholder: I18n.t('views.placeholder.title', field_name: I18n.t('activerecord.details.content')), required: true %>
          </div>
          <br>
          <div class="full-width-select">
            <label for="content_content_type"><%= I18n.t('views.label.content_type') %></label>
            <select name="content[content_type]" onclick="select_option('<%= lesson.id %>')" id="content_type<%= lesson.id %>">
              <option selected="selected" value="text">Text</option>
              <option value="pdf">Pdf</option>
              <option value="image">Image</option>
              <option value="video">Video</option>
            </select>
          </div>
          <br>
          <div id="text_type<%=lesson.id%>">
            <%= form.label I18n.t('activerecord.attributes.description') %> <br>
            <%= form.text_area :description, style: 'width:100%;', placeholder: I18n.t('views.placeholder.description', field_name: I18n.t('activerecord.details.content')) %>
          </div>
          <div id="file_type<%=lesson.id%>" style="display: none;">
            <%= form.label I18n.t('views.label.upload_file') %> <br>
            <%= file_field_tag :files %>
          </div>
          <br>
          <div class="row">
            <div class="col-6">
              <%= form.submit I18n.t('views.button.add'), class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  function select_option(lesson_id){
      var contentTypeSelect = document.getElementById("content_type"+lesson_id);
      var textTypeDiv = document.getElementById('text_type'+lesson_id);
      var fileTypeDiv = document.getElementById('file_type'+lesson_id);
      toggleDivVisibility();
      if (textTypeDiv.value === '')
          textTypeDiv.value = 'Enter your descriptions'
      contentTypeSelect.addEventListener('change', toggleDivVisibility);
      function toggleDivVisibility() {
          var selectedValue = contentTypeSelect.value;
          if (selectedValue === 'text') {
              textTypeDiv.style.display = 'block';
              fileTypeDiv.style.display = 'none';
          } else {
              textTypeDiv.style.display = 'none';
              fileTypeDiv.style.display = 'block';
          }
      }
  }
</script>

app/views/courses/_new_lesson_collapse.html.erb
<div id="demo" class="collapse">
  <div style="width: 600px;">
    <div class="card m-3">
      <div class="card-body">
        <%= form_with(model: @lesson, url: "/dashboard/add_lesson/#{@course.id}") do |form| %>
          <div class="mt-4">
            <%= form.label I18n.t('activerecord.attributes.title') %> </br>
            <%= form.text_field :title, style: 'width:100%', placeholder: I18n.t('views.placeholder.title', field_name: I18n.t('activerecord.details.lesson')), required: true %>
            <% @lesson.errors.full_messages_for(:title).each do |message| %>
              <div class="text-danger"><%= message %></div>
            <% end %>
          </div>
          <div class="mt-4">
            <%= form.label I18n.t('activerecord.attributes.score') %> </br>
            <%= form.text_field :score, style: 'width:100%', placeholder: I18n.t('views.placeholder.score'), min: 1, max: 10 , required: true %>
            <% @lesson.errors.full_messages_for(:score).each do |message| %>
              <div class="text-danger"><%= message %></div>
            <% end %>
          </div> </br>
          <div>
            <%= form.label I18n.t('activerecord.attributes.description') %> <br>
            <%= form.text_area :description, style: 'width:100%;', placeholder: I18n.t('views.placeholder.description', field_name: I18n.t('activerecord.details.lesson')), required: true %>
            <% @lesson.errors.full_messages_for(:description).each do |message| %>
              <div class="text-danger"><%= message %></div>
            <% end %>
          </div>
          <br>
          <div class="row">
            <div class="col-6">
              <%= form.submit I18n.t('views.button.add'), class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/courses/_show_image.html.erb
<div class="modal" id="myModal<%= content.id %>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= content.title %></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        <div class="row" style="font-size: medium">
          <% if content.content_type == "image" %>
            <%= image_tag content.files if content.files.present? %>
          <% elsif content.content_type == "video" %>
            <%= video_tag url_for(content.files), controls: true, preload: 'none' %>
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal"><%= I18n.t('views.button.close') %></button>
      </div>
    </div>
  </div>
</div>

app/views/courses/edit_course.html.erb
<div style="width: 500px; margin: 0 auto;">
  <div class="card m-3">
    <div class="card-header">
      <h5> <%= I18n.t('views.inner_text.courses.edit_course') %> </h5>
    </div>
    <div class="card-body">
      <%= form_with(model: @course, url: "/dashboard/edit_course/#{@course.id}") do |form| %>
        <div class="mt-4">
          <%= form.label I18n.t('activerecord.attributes.title') %> </br>
          <%= form.text_field :title, style: 'width:100%', placeholder: I18n.t('views.placeholder.title', field_name: I18n.t('activerecord.details.course')), required: true %>
          <% @course.errors.full_messages_for(:title).each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        </div>
        <div>
          <%= form.label I18n.t('activerecord.attributes.description')  %> <br>
          <%= form.text_area :description, style: 'width:100%;', placeholder: I18n.t('views.placeholder.description', field_name: I18n.t('activerecord.details.course')), required: true %>
          <% @course.errors.full_messages_for(:description).each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        </div>
        <br>
        <div class="row">
          <div class="col-6">
            <%= form.submit I18n.t('views.button.update'),class: 'btn btn-primary'  %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/new_course.html.erb
<div style="width: 500px; margin: 0 auto;">
  <div class="card m-3">
    <div class="card-header">
      <h5><%= I18n.t('views.inner_text.courses.add_course') %></h5>
    </div>
    <div class="card-body">
      <%= form_with(model: @course, url: dashboard_add_course_path) do |form| %>
        <div class="mt-4">
          <%= form.label I18n.t('activerecord.attributes.title') %> </br>
          <%= form.text_field :title, style: 'width:100%', placeholder: I18n.t('views.placeholder.title', field_name: I18n.t('activerecord.details.course')), required: true %>
          <% @course.errors.full_messages_for(:title).each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        </div>
        <div>
          <%= form.label I18n.t('activerecord.attributes.description') %> <br>
          <%= form.text_area :description, style: 'width:100%;', placeholder:  I18n.t('views.placeholder.description', field_name: I18n.t('activerecord.details.course')), required: true %>
          <% @course.errors.full_messages_for(:description).each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        </div>
        <br>
        <div class="row">
          <div class="col-6">
            <%= form.submit I18n.t('views.button.add'),class: 'btn btn-primary'  %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/show_course.html.erb
<div class="row">
  <% @courses.each do |course| %>
    <div class="col-4 mb-3">
      <div class="card" style="min-height: 200px;">
        <div class="card-header">
          <h4><%= course.title %></h4>
          <% if current_user.admin? %>
            <p style="font-size: 12px;">Owner: <i><%= course.users.first.name %></i></p>
          <% end %>
        </div>
        <div class="card-body"><p><%= course.description %></p></div>
        <div class="card-footer">
          <%= link_to I18n.t('views.button.details'), "/dashboard/show_a_course/#{course.id}", class: "btn btn-sm btn-secondary" %>
          <% if policy(course).edit_course? %>
            <%= link_to I18n.t('views.button.edit'), "/dashboard/edit_course/#{course.id}", class: "btn btn-sm btn-success" %>
          <% end %>
          <% if policy(course).destroy_course? %>
            <%= link_to I18n.t('views.button.assign'), "/dashboard/enroll_course/#{course.id}", class: "btn btn-sm btn-info" %>
          <% end %>
          <% if policy(course).destroy_course? %>
            <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#myModal<%= course.id %>">
              <%= I18n.t('views.button.delete') %>
            </button>
            <div class="modal" id="myModal<%= course.id %>">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title"><%= I18n.t('views.button.delete') %></h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                  </div>
                  <div class="modal-body">
                   <%= I18n.t('views.inner_text.courses.delete_confirmation_message') %>
                  </div>
                  <div class="modal-footer">
                    <%= form_with url: "/dashboard/delete_course/#{course.id}", method: :delete do |form| %>
                      <%= form.button I18n.t('views.button.delete'), class: 'nav-link btn-danger' %>
                    <% end %>
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal"><%= I18n.t('views.button.close') %></button>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/show_single_course.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title "><%= @course.title %>
      <% if policy(@course).edit_course? %>
        <button class="btn btn-sm btn-info" data-bs-toggle="collapse" data-bs-target="#demo"><%= I18n.t('views.button.add_lesson') %></button>
      <% end %>
      <% enrollment = Enrollment.where(course_id: @course.id, user_id: current_user.id).first %>
      <% if current_user.learner? || !policy(@course).edit_course? %>
        <% if enrollment.present? %>
          <% gained_score = UserCourseProgress.joins(:lesson).where(enrollment_id: enrollment.id).pluck(:score).sum %>
          <% total_score = Lesson.where(course_id: @course.id).pluck(:score).sum %>
          <p style="font-size: 16px;color: green">
            <% if gained_score == total_score && total_score != 0 %>
              <%= I18n.t('views.inner_text.lessons.completed') %>
            <% else %>
              Your Score: <%= gained_score %> / <%= total_score %></p>
            <% end %>

        <% end %>
      <% end %>
    </h2>
    <p class="card-text"><%= @course.description %></p>
    <%= render 'new_lesson_collapse' %>
    <br>
    <br>
    <h5><%= I18n.t('views.inner_text.courses.course_content') %></h5>
    <br>
    <div class="accordion" id="accordionExample">
      <% @course.lessons.each do |lesson| %>
        <div class="accordion-item mb-2">
          <h2 class="accordion-header" id="heading<%= lesson.id %>">
            <div class="row">
              <div class="col-10">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= lesson.id %>" aria-expanded="false" aria-controls="collapse<%= lesson.id %>">
                  <h6><%= lesson.title %> <b style="color:red">(<%= lesson.score %> Points)</b></h6>
                </button>
                <%= render partial: 'new_content_collapse', locals: { lesson: lesson } %>
              </div>
              <div class="col-2">
                <% if policy(lesson).edit_lesson? %>
                  <button class="btn btn-sm btn-info" data-bs-toggle="collapse" data-bs-target="#demo<%= lesson.id %>">
                    <%= I18n.t('views.button.add_content') %>
                  </button>
                  <%= link_to I18n.t('views.button.edit'), "/dashboard/edit_lesson/#{lesson.id}", class: "btn btn-sm btn-success" %>
                <% end %>
                <% if policy(lesson).destroy_lesson? %>
                  <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#myModal<%= lesson.id %>">
                    <%= I18n.t('views.button.delete') %>
                  </button>
                  <%= render partial: 'delete_modal', locals: { lesson: lesson } %>
                <% end %>
                <% unless policy(lesson).destroy_lesson? %>
                  <% enrollment = Enrollment.where(course_id: @course.id, user_id: current_user.id).first %>
                  <% course_progress = UserCourseProgress.where(lesson_id: lesson.id, user_id: current_user.id, enrollment_id: enrollment.id).first %>
                  <% if course_progress.present? && course_progress.complete_status %>
                    <button class="btn btn-sm btn-success"><%= I18n.t('views.inner_text.lessons.completed') %></button>
                  <% else %>
                    <%= form_with(url: "/dashboard/complete_lesson/#{lesson.id}", method: :post) do |form| %>
                      <%= form.hidden_field :enrollment_id, value: enrollment.id %>
                      <%= form.submit I18n.t('views.button.complete'), class: "btn btn-sm btn-secondary" %>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </h2>
          <div id="collapse<%= lesson.id %>" class="accordion-collapse collapse" aria-labelledby="heading<%= lesson.id %>" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <%= lesson.description %>
              <% lesson.contents.each do |content| %>
                <% if content.content_type == 'text' %>
                  <div class="row mt-3 mb-3">
                    <div class="row" style="font-size: medium">
                      <div class="col-10">
                        <b><%= content.title %>  (<%= content.content_type %>) </b>
                      </div>
                      <div class="col-2">
                        <% if policy(content).destroy_content? %>
                          <%= render partial: 'delete_content_button', locals: { content: content } %>
                        <% end %>
                      </div>
                    </div>
                    <div class="row" style="font-size: small">
                      <p><%= content.description %></p>
                    </div>
                  </div>
                <% elsif content.content_type == 'pdf' %>
                  <div class="row">
                    <div class="col-10">
                      <%= link_to content.title, url_for(content.files), target: "_blank" %>
                    </div>
                    <div class="col-2">
                      <% if policy(content).destroy_content? %>
                        <%= render partial: 'delete_content_button', locals: { content: content } %>
                      <% end %>
                    </div>
                  </div>
                <% else %>
                  <div class="row mb-3 text-left">
                    <div class="col-10">
                      <button type="button" class="btn btn-sm btn-secondary text-start" data-bs-toggle="modal" data-bs-target="#myModal<%= content.id %>">
                        <%= content.title %>  <b>(<%= content.content_type %>)</b>
                      </button>
                      <%= render partial: 'show_image', locals: { content: content } %>
                    </div>
                    <div class="col-2">
                      <% if policy(content).destroy_content? %>
                        <%= render partial: 'delete_content_button', locals: { content: content } %>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>